name: Activate_Bukkit_Plugin
main: me.crosant.activate_bukkit_plugin.activate_bukkit_plugin
version: 0.1
commands:
    activate:
          description: Activate
          usage: /<command> arg
permissions:
    Activate_Bukkit_Plugin.*:
        description: Gives access to all Activate commands
        children:
            Activate_Bukkit_Plugin.refresh: true
            Activate_Bukkit_Plugin.reload: true
    doorman.reload:
        description: Allows you to reload Activate
        default: op
    doorman.refresh:
        description: Allows you to refresh activation string
        default: op
depend: [Permissions, PermissionsEx]